application: tcga-mutation-hotspots-webapp
version: dev
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: MySQLdb
  version: "latest"
- name: ssl
  version: "latest"

builtins:
- django_wsgi: on
- remote_api: on
- appstats: on
- deferred: on

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/imgfavicon.ico
- url: /static
  static_dir: static
- url: /.*
  script: main.application
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

env_variables:
  DJANGO_SETTINGS_MODULE: 'hotspots.settings'
